<!DOCTYPE HTML>
<html lang="zh">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="description" content="C/C++ 安全编程要点：捕获过于宽泛的异常，如捕获 std::exception、std::logic_error、std::runtime_error 等类型的异常，或使用 catch(...) 子句捕获所有异常，会使异常处理失去针对性，而且很可能会将本不应处理的异常一并捕获。" />
  <link type="text/css" rel="stylesheet" href="../css/detail.css" />
  <link type="image/x-icon" rel="shortcut icon" href="../favicon.png" />
  <script src="../js/search.js"></script>
  <script src="../js/iconfont.js"></script>
  <title>不应捕获过于宽泛的异常 - C/C++ 安全规则</title>
</head>
<div class="footer-holder">
<nav>
  <ul class="nav-list">
    <li><span class="nav-icon">☰</span></li>
    <li><a href="../index.html">首页</a></li>
    <li><a href="../index.html#rules-class-title">规则分类</a></li>
    <li><a href="./introduction.html">项目介绍</a></li>
  </ul>
  <div class="nav-stuff"></div>
  <div class="search-box">
    <input type="text" id="search-input" placeholder="Search..." onkeydown="onKeyDownForSearch(event)" />
    <img alt="search" id="search-icon" src="../img/search.svg" onclick="onClickSearchIcon(this)"/>
  </div>
  <span class="nav-ellipsis">•••</span>
</nav>
<article>
<header>
  <h1>不应捕获过于宽泛的异常</h1>
  <div id="subtitle">
    <div id="subtitle-id">7.4 ID_catch_generic</div>
    <div id="subtitle-tags">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-standard"></use></svg><a class="rule-toc-link" href="../index.html#exception">目录</a> › <a class="rule-toc-link" href="./ID_throwNonExceptionType.html">next</a> › <a class="rule-toc-link" href="./ID_throwGenericException.html">previous</a>
    </div>
  </div>
  <hr class="solid-hr"/>
</header>
<main>
<p>捕获过于宽泛的异常，如捕获 std::exception、std::logic_error、std::runtime_error 等类型的异常，或使用 catch(...) 子句捕获所有异常，会使异常处理失去针对性，而且很可能会将本不应处理的异常一并捕获。</p>

<p>示例：</p>
<pre><code>class WrongArg {};

void foo(int a) try
{
    if (a &lt; 0) {
        throw WrongArg();
    }
    bar(a);   //<i> Other exceptions may be thrown</i>
}
catch (...)   //<i> Non-compliant</i>
{
    std::cout &lt;&lt; &quot;wrong argument\n&quot;;
}</code></pre>
<p>例中 foo 函数在参数不符合要求时抛出异常，bar 函数会抛出其他异常，用 catch(...) 子句将所有异常都当作“参数不符合要求”是不合理的。</p>

<p>例外：</p>
<pre><code>try
{
    ext_interface();   //<i> External interface</i>
}
catch (std::exception&amp; e)   //<i> Let it go, but comments are required</i>
{
    log(e.what());
}
catch (...)   //<i> Let it go, but comments are required</i>
{
    log(&quot;unknown exception&quot;);
}</code></pre>
<p>当不受控制的外部代码会抛出未知的异常时，可酌情捕获宽泛类型的异常，但应配以文档说明问题。</p>

</main>

<h3>相关</h3>
<div class="ref-items"><a href="./ID_throwGenericException.html" class="related-link">ID_throwGenericException</a></div>


<h3>参考</h3>
<div class="ref-items"><a href="https://cwe.mitre.org/data/definitions/396.html" target="_blank" class="related-link">CWE-396</a></div>
</article>
</div>
<footer>
  <a href="https://www.apache.org/licenses/LICENSE-2.0">Copyright©2024 360 Security Technology Inc., Licensed under the Apache-2.0 license.</a>
</footer>
</html>
