<!DOCTYPE HTML>
<html lang="zh">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="description" content="C/C++ 安全编程要点：重新抛出异常时应使用空 throw 表达式，避免异常对象的精度损失和不必要的复制开销。" />
  <link type="text/css" rel="stylesheet" href="../css/detail.css" />
  <link type="image/x-icon" rel="shortcut icon" href="../favicon.png" />
  <script src="../js/iconfont.js"></script>
  <title>重新抛出异常时应使用空 throw 表达式（throw;） - C/C++ 安全规则</title>
</head>
<article>
<header>
  <h1>重新抛出异常时应使用空 throw 表达式（throw;）</h1>
  <div id="subtitle">
    <div id="subtitle-id">7.20 ID_improperRethrow</div>
    <div id="subtitle-tags">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-standard"></use></svg> <a class="nav-link" href="../index.html#exception">Home</a> › <a class="nav-link" href="./ID_rethrowOutOfCatch.html">next</a> › <a class="nav-link" href="./ID_catch_justRethrow.html">previous</a>
    </div>
  </div>
  <hr class="dashed-hr"/>
</header>
<main>
<p>重新抛出异常时应使用空 throw 表达式，避免异常对象的精度损失和不必要的复制开销。</p>

<p>示例：</p>
<code>class Base {};
class Derive: public Base {};

void foo() {
    try {
        throw Derive();
    }
    catch (Base&amp; e) {
        throw e;        //<i> Non-compliant, use ‘throw;’ instead</i>
    }
}

void bar() {
    try {
        foo();
    }
    catch (Derive&amp; e) {   //<i> Cannot catch Derive</i>
        ....
    }
}
</code>
<p>注意，例中 foo 函数虽然捕获的是 Derive 对象，但 throw e; 抛出的是 Base 对象，这也是一种“<a href="https://en.wikipedia.org/wiki/Object_slicing" target="_blank" class="dashed-link">对象切片</a>”问题，造成了对象类型的“精度损失”。将 throw e; 改为 throw; 可解决这种问题。</p>

</main>


<h3>依据</h3>
<hr class="dashed-hr"/>
<div class="ref-items">ISO/IEC 14882:2003 15.1(6)
ISO/IEC 14882:2011 15.1(8)</div>


</article>
</html>
