<!DOCTYPE HTML>
<html lang="zh">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <link type="text/css" rel="stylesheet" href="../css/detail.css"/>
  <link type="image/x-icon" rel="shortcut icon" href="../favicon.png"/>
  <title>不应在 catch 子句外使用空 throw 表达式（throw;） - C/C++ 安全规则</title>
</head>
<script src="../js/iconfont.js"></script>
<article>
<header>
  <h1>不应在 catch 子句外使用空 throw 表达式（throw;）</h1>
  <div id="subtitle">
    <div id="subtitle-id">ID_rethrowOutOfCatch</div>
    <div id="subtitle-tags">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-standard"></use></svg> <a class="nav-link" href="../index.html">Home</a> › <a class="nav-link" href="./ID_throwPointer.html">next</a> › <a class="nav-link" href="./ID_improperRethrow.html">previous</a>
    </div>
  </div>
  <hr class="dashed-hr"/>
</header>
<div class="main-p">
空 throw 表达式用于重新抛出当前捕获的异常，用在 catch 子句外是危险的，增大了流程控制的复杂性。

如果当前没有异常被捕获，空 throw 表达式会引发 std::terminate 函数的执行，导致程序异常终止。

示例：
<div class="code">void foo() {
    throw;     //<span class="comment"> Non-compliant</span>
}

void bar() {
    try {
        throw;   //<span class="comment"> Non-compliant</span>
    }
    catch (...) {   //<span class="comment"> Cannot catch ‘throw;’</span>
        ....
    }
}</div>

</div>


<h3>依据</h3>
<hr class="dashed-hr"/>
<p class="main-p">ISO/IEC 14882:2003 15.1(6 8)
ISO/IEC 14882:2003 15.3(9)-implementation
ISO/IEC 14882:2011 15.1(8 9)
ISO/IEC 14882:2011 15.3(9)-implementation

</p>

<h3>参考</h3>
<hr class="dashed-hr"/>
<p class="main-p">MISRA C++ 2008 15-1-3

</p>
</article>
</html>
