<!DOCTYPE HTML>
<html lang="zh">
<head>
  <meta charset="utf-8">
  <link type="text/css" rel="stylesheet" href="../css/detail.css"/>
  <link type="image/x-icon" rel="shortcut icon" href="../favicon.png"/>
  <title>不应抛出过于宽泛的异常 - C/C++ 安全规则</title>
</head>
<script src="../js/iconfont.js"></script>
<article>
<header>
  <h1>不应抛出过于宽泛的异常</h1>
  <div id="subtitle">
    <div id="subtitle-id">ID_throwGenericException</div>
    <div id="subtitle-tags">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-standard"></use></svg> <a class="nav-link" href="../index.html">Home</a> › <a class="nav-link" href="./ID_catch_generic.html">next</a> › <a class="nav-link" href="./ID_uncaughtException.html">previous</a>
    </div>
  </div>
  <hr class="dashed-hr"/>
</header>
<div class="main-p">
抛出过于宽泛的异常，如 std::exception、std::logic_error、std::runtime_error 等类型的异常，会使异常处理失去针对性，而且处理这种异常时很可能会将本不应处理的异常一并捕获。

示例：
<div class="code">void foo(int a) try
{
    if (a &lt; 0) {
        throw std::exception();   //<span class="comment"> Non-compliant</span>
    }
    bar(a);   //<span class="comment"> Other exceptions may be thrown</span>
}
catch (std::exception&amp;)   //<span class="comment"> Other exceptions are also caught</span>
{
    std::cout &lt;&lt; &quot;wrong argument\n&quot;;
}</div>
foo 函数在参数不符合要求时抛出 std::exception 类的异常，过于宽泛，如果 bar 函数抛出从 std::exception 派生的其他异常，也会被当作“参数不符合要求”处理。

应为异常定义具体的类：
<div class="code">class WrongArg {};

void foo(int a) try
{
    if (a &lt; 0) {
        throw WrongArg();   //<span class="comment"> Compliant</span>
    }
    bar(a);
}
catch (WrongArg&amp;)   //<span class="comment"> Right</span>
{
    std::cout &lt;&lt; &quot;wrong argument\n&quot;;
}</div>

</div>

<h3>相关</h3>
<hr class="dashed-hr"/>
<p class="main-p"><a href="./ID_catch_generic.html" target="_blank" class="related-link">ID_catch_generic</a>

</p>


<h3>参考</h3>
<hr class="dashed-hr"/>
<p class="main-p">CWE-397

</p>
</article>
</html>
